//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 04:32:48 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dxc.com/request/")
package com.dxc.surrendertransaction.request;
